spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;connectTimeout=60000&amp;socketTimeout=60000&amp;useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: kaikxingx1


